import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthGuard from "@/components/AuthGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen text-black bg-gradient-to-b from-[#FEFFFF] via-[#FFFFFF] to-[#C8E5FF] overflow-x-hidden`}
      >

        {/* Global Background Image */}


        {/* Global Layout Wrapper */}
        <AuthGuard>
          <main className="flex-grow">
            {children}
          </main>
        </AuthGuard>
      </body>
    </html>
  );
}
